/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as FormsIndexImport } from './routes/forms/index'
import { Route as SubmissionFormIdImport } from './routes/submission/$formId'
import { Route as FormsFormIdImport } from './routes/forms/$formId'
import { Route as BuilderFormIdImport } from './routes/builder/$formId'
import { Route as AuthSignUpImport } from './routes/auth/sign-up'
import { Route as AuthLoginImport } from './routes/auth/login'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FormsIndexRoute = FormsIndexImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => rootRoute,
} as any)

const SubmissionFormIdRoute = SubmissionFormIdImport.update({
  id: '/submission/$formId',
  path: '/submission/$formId',
  getParentRoute: () => rootRoute,
} as any)

const FormsFormIdRoute = FormsFormIdImport.update({
  id: '/forms/$formId',
  path: '/forms/$formId',
  getParentRoute: () => rootRoute,
} as any)

const BuilderFormIdRoute = BuilderFormIdImport.update({
  id: '/builder/$formId',
  path: '/builder/$formId',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof rootRoute
    }
    '/builder/$formId': {
      id: '/builder/$formId'
      path: '/builder/$formId'
      fullPath: '/builder/$formId'
      preLoaderRoute: typeof BuilderFormIdImport
      parentRoute: typeof rootRoute
    }
    '/forms/$formId': {
      id: '/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/forms/$formId'
      preLoaderRoute: typeof FormsFormIdImport
      parentRoute: typeof rootRoute
    }
    '/submission/$formId': {
      id: '/submission/$formId'
      path: '/submission/$formId'
      fullPath: '/submission/$formId'
      preLoaderRoute: typeof SubmissionFormIdImport
      parentRoute: typeof rootRoute
    }
    '/forms/': {
      id: '/forms/'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/builder/$formId': typeof BuilderFormIdRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/submission/$formId': typeof SubmissionFormIdRoute
  '/forms': typeof FormsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/builder/$formId': typeof BuilderFormIdRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/submission/$formId': typeof SubmissionFormIdRoute
  '/forms': typeof FormsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/builder/$formId': typeof BuilderFormIdRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/submission/$formId': typeof SubmissionFormIdRoute
  '/forms/': typeof FormsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/sign-up'
    | '/builder/$formId'
    | '/forms/$formId'
    | '/submission/$formId'
    | '/forms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/sign-up'
    | '/builder/$formId'
    | '/forms/$formId'
    | '/submission/$formId'
    | '/forms'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/sign-up'
    | '/builder/$formId'
    | '/forms/$formId'
    | '/submission/$formId'
    | '/forms/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  BuilderFormIdRoute: typeof BuilderFormIdRoute
  FormsFormIdRoute: typeof FormsFormIdRoute
  SubmissionFormIdRoute: typeof SubmissionFormIdRoute
  FormsIndexRoute: typeof FormsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  BuilderFormIdRoute: BuilderFormIdRoute,
  FormsFormIdRoute: FormsFormIdRoute,
  SubmissionFormIdRoute: SubmissionFormIdRoute,
  FormsIndexRoute: FormsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/login",
        "/auth/sign-up",
        "/builder/$formId",
        "/forms/$formId",
        "/submission/$formId",
        "/forms/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up.tsx"
    },
    "/builder/$formId": {
      "filePath": "builder/$formId.tsx"
    },
    "/forms/$formId": {
      "filePath": "forms/$formId.tsx"
    },
    "/submission/$formId": {
      "filePath": "submission/$formId.tsx"
    },
    "/forms/": {
      "filePath": "forms/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
